title: Veilon.org
description: Cybersecurity insights
email: echonest@veilon.org
author:
  name: "0xEch0_N3st"



  
url: "https://veilon.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # or "neon", "contrast", "mint", etc.
minimal_mistakes_stylesheet: /assets/css/main.css
locale: "en-US"
search: true
read_time: true


social:
  github: https://github.com/EchoN3st
  twitter: https://twitter.com/0xEch0_N3st
  email: echonest@veilon.org

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: custom-post
      author_profile: false
      read_time: true
      comments: false
      share: false

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

permalink: /:categories/:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"
collections:
  posts:
    output: true
    permalink: /:title/
